name: "Setup"
description: "Checkout, setup node, and install dependencies"
runs:
  using: "composite"
  steps:
    - name: Checkout with ref
      uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Checkout without ref
      uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
      shell: bash
