name: "CI"
description: "Run Biome"
runs:
  using: "composite"
  steps:
    - name: Setup Biome
      uses: biomejs/setup-biome@v2
      with:
        version: latest
    - name: Run Biome
      run: biome ci .
      shell: bash
