name: CI
on:
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/lint

  test:
    runs-on: ubuntu-latest
    needs: lint # 👈 only runs if lint succeeded
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/test
        with:
          api_url: ${{ secrets.API_URL }}
          ui_url: ${{ secrets.UI_URL }}
