name: E2E Tests
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: ./.github/actions/setup
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: ./.github/actions/test